### ISSUE TITLE
:bug: Reset does not work on physical hardware (INTEL NUC as Example)

### ISSUE THREAD

**Issue by 3pings** [kairos-io/kairos#1178]
**Kairos version:**
1.5,1.6,2.0

**CPU architecture, OS, and Version:**
x86 12 Generation Intel.  OS version does not matter.  The result is the same.

**Describe the bug**
When sending a node to reset, the node never comes back online.  It simply sits at a blank screen.  The node boots into recovery, but the reset command is never applied.

**To Reproduce**
Load an Intel NUC and send it to reset.

**Expected behavior**
The Node should reset back to the original state.

**Comment by mudler** [comment]
on real hardware works here - I guess this is just specific to a custom setup? Can you provide more informations, like:

- cloud config used for the installation
- steps to reproduce (how did you triggered the reset? with Kubernetes? manually?)
- Is this EFI or MBR installations? is that using UEFI and the shim?

Thanks!

**Comment by Itxaka** [comment]
![image](https://user-images.githubusercontent.com/1447686/226953166-7cabd923-b15d-4f13-b159-cdb32006e5c4.png)

**Comment by Itxaka** [comment]
The error on the image comes exactly from here: https://github.com/kairos-io/elemental-cli/blob/main/pkg/config/config.go#L382

That only triggers if the efi dir exists in the current system: https://github.com/kairos-io/elemental-cli/blob/main/pkg/config/config.go#L367

The dir that its being check its `/sys/firmware/efi` which is mounted by default if we are on an efi system (booted via efi) and its done by the kernel: https://renenyffenegger.ch/notes/Linux/fhs/sys/firmware/efi/index

The only way that can happen is, if the machine is EFI but it was installed with bios?? When installing in bios mode, the efi partition WONT be created but the system will still have the efi directory. But AFAIK you should not be able to boot in EFI mode with bios....


@3pings is the machine booting in one of those mixed modes where it tries EFI and fallbacks to legacy? That may be able to create this situation.

Is it possible to get a lsblk/blkid of the machine to see the actual partitions?

**Comment by mudler** [comment]
as discussed in the chat: could be likely that IF the config is with `fast` enabled, then it might not give enough time for user data to finish pulling in the background, thus elemental cannot access partitions.

In any case, we should wait user-data, as we do in the installation for the same reason: https://github.com/kairos-io/kairos/blob/1852c658ff7c4eb85c7369b5bc8735d25eaba666/internal/agent/install.go#L121

**Comment by mudler** [comment]
@3pings can you confirm that the cloud-config you are using has the `fast` flag enabled? https://github.com/kairos-io/kairos/blob/1852c658ff7c4eb85c7369b5bc8735d25eaba666/internal/agent/config.go#L27

**Comment by Itxaka** [comment]
It was confirmed that the `fast`option was used so it looks like something has the disk open while reset is working which makes elemental not able to open the disk.

Waiting for reports that if removing the fast key makes it work, in which case we should:

 - open an issue to test the fast option
 - open an issue to make elemental-cli NOT return an empty partition list if it cant open the disk, but instead FAIL with a proper error or at least LOG that error properly so the issue is visible. Also adding a retry in there would be nice.


Im wondering if the linuxkit/metadata issue that kept the disks open is the culprit. After all Im not sure the fix was in by the time we cut 2.0.0-alpha1

@3pings Can you check what elemental version is being used in those systems? `elemental-cli version --long` should give the full version commit included

**Comment by mudler** [comment]
`fast` is confirmed that was used, looks like we need to https://github.com/kairos-io/kairos/blob/1852c658ff7c4eb85c7369b5bc8735d25eaba666/internal/agent/install.go#L121 as well during reset
