### ISSUE TITLE
🤖 QA/tests: elemental upgrade process

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1286]
**Is your feature request related to a problem? Please describe.**
Not really, this is a QA card to check that behavior is still consistent, and to add specific e2e tests for it

**Describe the solution you'd like**
in the first embrional PoC of cOS (then renamed elemental, etc) the bash script did this during upgrade:

if currently booting from active:
1. create transition image, add labels for the active system
1. create the new passive image from the current active
1. rewrite labels on the new passive image just created
1. replace the active image with the transition image just created in step 1
1. replace the passive image with the new passive image just created in step 2

if currently booting from passive:
1. create transition image, adding labels for active
1. replace current active image in the system with transition image
1. stop!

This is for 2 reasons:
- atomic operations - if you unplug the power, in any of those phases, the system is still capable to boot (active, or passive) depending on when that happens
- if you try to upgrade from the passive, means likely a previous upgrade failed, and as such we want just to replace the active image (and keep the fallback at a "last known good working")

This card is about:

- Making the process is consistent with the steps above
- Add e2e QA checks in this repo that assess the image swap, and the steps above

If the above doesn't hold - create a new issue to fix the behavior and split the QA tests into another card

**Comment by Itxaka** [comment]
>   create transition image, add labels for the active system
 >   create the new passive image from the current active
 >   rewrite labels on the new passive image just created
 >   replace the active image with the transition image just created in step 1
 >  replace the passive image with the new passive image just created in step 2


current state for normal upgrade (not recovery):


If booting from active:
 1 - Create transition image, mount it under /run/cos/transition, copy source into transition dir
 2 - Backup Active into passive
 3 - Label passive (because its a copy it will have the COS_ACTIVE label until now)
 4 - Move transition image into active image

So this syncs with what is expected I think. In the requested workflow, passive is not done until the end which is kind of bad IMO, passive should be done ASAP in the workflow in case anything with the active happens, so at least passive is covered.


Now, on booting from passive, the steps are the same, there is no current difference between them unfortunately.

So we need to do the passive workflow to do just the active substitution.
