### ISSUE TITLE
:sparkles: Extract kairos-agent to its own repository

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1346]
The [kairos-io/kairos](https://github.com/kairos-io/kairos) should only keep "OS files", those are files needed to build the various flavors of kairos (e.g. overlay files). The kairos-agent binary will be split to another repository.

## Acceptance Criteria

- There is a `kairos-io/kairos-agent` repository
- There is CI to build the binary and release it as a luet package
- The repository has enough tests to ensure we don't release broken binaries. Options:
  - Copy some tests currently in `kairos-io/kairos` but only runs them with one flavor (not matrices).
  - Create some kairos-agent specific tests that only test "install/upgrade/reset" functionality.
- `kairos-io/kairos` consumes the kairos-agent as a luet package
- `kairos-io/kairos` still runs all tests for all flavors (like it does now).

Blocking this: https://github.com/kairos-io/kairos/issues/1210

**Comment by Itxaka** [comment]
First pass: https://github.com/kairos-io/kairos-agent

Issues:

 - Docs. Currently under kairos repo but agent needs to bundle them. Its ok because we can import the docs into the earthly of kairos-agent and bundle them with the webui. Works as expected.
 - Schema. Generated by kairos-agent, but part of the docs. Can be done on the kairos earhtfile by just installing the kairos-agent package and running the schema.

Both of the above at the same time: agent bundles the docs. But docs want the schema. But that requires the agent. Which bundles the docs. etc...


We have to make sure that:
 - on release, we generate the schema from the installed agent so it matches the agent version.
 - on agent build, we generate the schema as part of the docs bundling
 - we dont have a recurring dep of one thing trying to build the other and that other trying to build the first. 


Or we look for a different solution, like building the docs as part of the agent only adn publishing the docs as part fo the agent as well, so they are in sync with the agent, which sucks. Or having them separated somehow. Cant think of any good wayof doing it.

**Comment by Itxaka** [comment]
We agreed to move the docs out of the kairos repo and then install them as a luet package

**Comment by Itxaka** [comment]
Im wondering if that makes sense....

docs need agent to generate the schema of version X. But if we install them as a package it means that they have been built already, which means that the schema was built before....so how would we go to bundle the docs with a schema of version 5 if we are just cutting version 5?

I guess we could provider a kairos-schema package that uses kairos-agent to generate the schema of version X and install that as well?

So docs dont have the schema bundled but the kairos-schema package install the schema into /opt/kairos/schemas or whatever and the docs just point you to that dir for the schemas?

@mauromorales any idea how we could do this properly?

**Comment by Itxaka** [comment]
moved docs to https://github.com/kairos-io/kairos-docs

**Comment by Itxaka** [comment]
now no idea how its building it and what pushes it to kairos.io, nor how to configure the netlify stuff so waiting for @mudler to be back and deal with that 💯

**Comment by Itxaka** [comment]
Package PR to add kairos-agent https://github.com/kairos-io/packages/pull/193

**Comment by Itxaka** [comment]
PR to make kairos consume kairos-agent as package: https://github.com/kairos-io/kairos/pull/1354/

**Comment by Itxaka** [comment]
All merged, the only thing it misses its adding extra tests to kairos-agent.

Closing this and opening a new card for that.
