### ISSUE TITLE
✨ errors on boot of a derivative after upgrade from kairos 1.5 .to 2.0.3

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#1367]
**Kairos version:**
kairos 2.0.3

**CPU architecture, OS, and Version:**
ubuntu-22, amd 

**Describe the bug**
After upgrade of kairos from 1.5 to 2.0.3 the following attached errors show up on boot of a derivative image. These errors do not create an issue but show up during boot.

**To Reproduce**

**Expected behavior**
Since these errors do not cause an issue, these errors need to be switched to warn/ suppressed / removed.

**Logs**

**Additional context**

![image (3)](https://user-images.githubusercontent.com/504862/235335336-0dfb7498-1fcd-4bce-bd5e-841affde03e3.png)
![Screenshot 2023-04-26 at 6 00 25 PM (1)](https://user-images.githubusercontent.com/504862/235335341-6c387625-4bb5-49f8-9fc5-c35b120bf4f6.png)
![Screenshot 2023-04-27 at 1 01 18 PM (2)](https://user-images.githubusercontent.com/504862/235335343-6ed4addd-e6e0-462e-9fdb-55b12a065f20.png)

slack conversations here:
https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1682510972060869
https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1682513344014189
https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1682632044061259

**Comment by Itxaka** [comment]
Those issues are normal.

Blkid issue -> We try to get the fs of the mounts asap and that fails because at that point they arent mounted -> fake error message.

That is fixed in 0.0.20


Failure to mount snap/certs dirs -> Expected.
 - Snap is trying to mount in in / which is RO, unless the dir exists beforehand it wont be able to do so.
 - certs dir already exists and its not empty, so it will fail.

Both of those are just warning but its difficult to discern between a warning and a real failure (i.e. something went wrong and persistent is full so we cannot create the dir) so I left them as errors.

Same errors were already in Kairos and all cos-immutable-rootfs derivatives, they were just ignored and logged to journalctl where nobody checked them. Immucore makes them visible now :D
