### ISSUE TITLE
:sparkles: Run validations before customizing a RPi image

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1420]
**Is your feature request related to a problem? Please describe.**

When [customizing a RPi image](https://kairos.io/docs/installation/raspberry/#customizing-the-disk-image), if you made a mistake on your cloud config, you will only find out after building and copying to the SD card.

**Describe the solution you'd like**

Validations would run at the beginning of the process

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by jimmykarily** [comment]
We could add the `validate` command [to the kairosctl](https://github.com/kairos-io/provider-kairos/blob/main/cli/kairosctl/main.go) so that the users can at least run it manually. Doing that automatically when people use [the osbuilder flow](https://kairos.io/docs/installation/raspberry/#customizing-the-disk-image) would also be good.

**Comment by mauromorales** [comment]
I decided to add the command to kairosctl because I think it's going to be needed there anyway and updated the documentation. It's not solving #958 but I think that one will need a bit more thought
