### ISSUE TITLE
:bug: Fix issue with `karios-agent upgrade`

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1998]
We encountered the following issues for Kairos upgrade

```
# kairos-agent upgrade
WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
INFO[2023-11-10T11:32:39Z] kairos-agent version v2.3.0     
WARN[2023-11-10T11:32:39Z] failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory 
sanitizing the upgrade spec: undefined upgrade source
```

**Comment by jimmykarily** [comment]
If we are not calling `kairos-agent upgrade` without user interaction somewhere (e.g. by selecting a grub menu or something), then we could make this command interactive. E.g.

```
Found these releases:

1. ...
2. ...
3. ...

Which one do you want to upgrade to? : 
```

**Comment by santhoshdaivajna** [comment]
@jimmykarily we use it in the product to trigger upgrades _without user interaction_.

**Comment by jimmykarily** [comment]
> @jimmykarily we use it in the product to trigger upgrades _without user interaction_.

What do you upgrade to? We were wondering, at least in Kairos, if the user triggers an upgrade without specifying the image to use, what does the user mean? Do they want to upgrade to the latest Kairos version keeping the same kubernetes version? Or do they want to upgrade all to latest and greatest?

If you are providing the image through the `upgrade:` block in the kairos config, then that's different and it can be detected so that we don't prompt the user.

**Comment by jimmykarily** [comment]
This should be fixed first in any case: https://github.com/kairos-io/kairos/issues/1999

so that we have a way to list releases properly. Deciding what to release to comes after.

**Comment by mudler** [comment]
@jimmykarily @santhoshdaivajna I guess we can close this now, right?

**Comment by jimmykarily** [comment]
> @jimmykarily @santhoshdaivajna I guess we can close this now, right?

I'm fine closing it, unless there is a specific flow that can't be implemented (thus my questions above).

**Comment by jimmykarily** [comment]
Closing. If there is an issues, it will be reported I guess.
