### ISSUE TITLE
Localfile installation with runBundles 

### ISSUE THREAD

**Issue by santhoshdaivajna** [kairos-io/kairos#2000]
**Kairos version:**
Kairos 2.4.1
kairos-agent 2.3.0

**Describe the bug**
setting bundleConfig [LocalFile](https://github.com/kairos-io/kairos-sdk/blob/f37fc75b5dfadcb8b17d91ca8b47066ec68df881/bundles/bundles.go#L22) to true used to support usage of image.tar files available locally for installation or extraction in earlier releases. It's not working now and the OCIImageExtractor tries to pull the image from internet even though the files are available locally on the system.

**To Reproduce**
set bundleConfig LocalFile to _true_

**Expected behavior**
If bundleConfig LocalFile is set to _true_ and the image is available locally then image should not downloaded.

**Comment by mauromorales** [comment]
The issue was introduced on this commit: https://github.com/kairos-io/kairos-sdk/commit/ee38ccde541831c64fb602c87abce9d43657562a

where we removed the check for `LocalFile`: https://github.com/kairos-io/kairos-sdk/commit/ee38ccde541831c64fb602c87abce9d43657562a#diff-8e10d3eee9260dce2bf6cf7f8147d8052f350fb37c6c3e01c48d04852984b2efL194-L197

**Comment by jimmykarily** [comment]
Done, now we need to cut a new release os the `kairos-agent` package and bump it here.

**Comment by jimmykarily** [comment]
This is fixed since kairos-agent 2.4.4 , which was included in the framework images for a while now (e.g. https://github.com/kairos-io/kairos-framework/pull/28). The upcoming release will have this fix (as long as we consume a recent enough framework image).
