### ISSUE TITLE
UKI: Enroll keys during setup

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2048]
This card is a tracker for UEFI Setup mode implementation (to enroll SB keys automatically as part of the installation process)

Follow-up of https://github.com/kairos-io/kairos/issues/1151

**Comment by Itxaka** [comment]
Is this even possible?

You boot, go to bios and add the keys there, which are on the livecd/rootfs/uki EFI.

Otherwise you cannot boot if secureboot is enabled. And if you disabke it so you can boot our uki EFI file.... Not even sure if you can modify the keys when it's disabled.

In any case if you insert a key from user space you still need to get into something like mokmanager to confirm the installation I think.

This is something to discuss further because I don't understand the implications or it this is even possible as presented.

**Comment by mudler** [comment]
seems talos can: https://www.talos.dev/v1.5/talos-guides/install/bare-metal-platforms/secureboot/#generating-the-keys

**Comment by mudler** [comment]
Also arch: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot (search for Setup mode)

**Comment by Itxaka** [comment]
Interesting! Although removing the keys in order to make it on setup mode scares me 🤣

This means we also have to bundle the Microsoft keys with our db, interesting. I think there are a few python tools that can bundle keys...

**Comment by mudler** [comment]
this is done
