### ISSUE TITLE
🐛 Without the bus, other providers might not be able to upgrade

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2072]
This comes from the changes in https://github.com/kairos-io/kairos/issues/1999 and specifically the removal of https://github.com/kairos-io/provider-kairos/pull/496

**Comment by jimmykarily** [comment]
The hook was only removed from our provider. If other providers return something on that hook, that would still be respected by the `kairos-agent` (https://github.com/kairos-io/kairos-agent/pull/181/files#diff-2959e01701bea9b2e0f3f1df94ddbc81ed794f47aeac4496e4053725ddd94930R43) . Still, none of the other provider seem to have that implemented so I don't expect anything to be broken.

The implicit upgrade wasn't working anyway because we returned an error when the "source" wasn't explicitly set.

**Comment by mauromorales** [comment]
cc @Itxaka

**Comment by Itxaka** [comment]
Yes, seems that I'm wrong and interpreted the PR as removing the bus events thus no provider release list.

Sorry about that, this can be closed then
