### ISSUE TITLE
QR code display on ubuntu is broken

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#212]
**Kairos version:**
1.4.0

**CPU architecture, OS, and Version:**
Ubuntu flavors only

**Describe the bug**
The QR code on boot cannot be displayed correctly

**To Reproduce**
Boot the ubuntu flavor

**Expected behavior**
Have the QR code visible such as can be scanned with the CLI

**Logs**

**Additional context**

**Comment by jtcressy** [comment]
Is this the same issue as having odd diamond shapes in the QR code output? Just making sure so I don't accidentally file a duplicate issue. 

Here's an example of what I see when booting the ubuntu flavor from provider-kairos:
<details><summary>Expand</summary>

![image](https://user-images.githubusercontent.com/7663028/211125061-fa272439-fe64-468b-b499-0692ac8e0ad3.png)

</details>

**Comment by mudler** [comment]
yes, correct 👍 that's the issue we are tracking here

**Comment by jtcressy** [comment]
indeed, my workaround is editing the command line in grub at boot-time and removing `nomodeset`. It's odd that this argument works fine on all other flavors. must be something different about ubuntu's kernel display drivers.

**Comment by jtcressy** [comment]
@mudler I made a discovery on this issue while working with my own derivative

Our solution may simply be to:
1. install the package `console-data` which provides the font file at `/usr/share/consolefonts/default8x16.psf.gz`
    - this file is special because it seems to actually provide a unicode map while every other font shipped with the OS by default seems not to. In fact, this should be similar to the console font used by opensuse by default.
2. Override the font set by `setupcon` via `/etc/default/console-setup` and set `FONT="default8x16.psf.gz"` somewhere in the file - this should override other settings in the file and anything set via `dpkg-reconfigure console-setup`
---
How I got here:

I kept comparing the differences of opensuse and ubuntu when it comes to how they configure console fonts - opensuse seems to do something with systemd-vconsole-setup but ubuntu uses a different package entirely called simply "console-setup" which provides the binary `setupcon` which is just a wrapper for calling `setfont` on several TTY consoles. Thing is, `setupcon` only works with specially formatted font file names because it scrapes your locale config to determine which console font to use. e.g. it only works with files like `Uni3-Terminus8x16.psf.gz`, thus the file `default8x16.psf.gz` would never be selected by `setupcon` with the options given to you in `/etc/default/console-setup`. But! we can rely on an override by setting `FONT="default8x16.psf.gz"` in `/etc/default/console-setup` and `setupcon` will use that font regardless of locale config.

**Comment by jimmykarily** [comment]
@jtcressy thanks for debugging this and finding a fix! Let us try to put it in one of the next releases.

**Comment by mauromorales** [comment]
I tried applying the suggestions without much luck. However, I do notice that the issue is only present in console of my virtual manager. If I access via SSH the problem is not there.



![Image](https://user-images.githubusercontent.com/433958/213767819-52992d25-3d6c-490c-b905-daf9f5e0b9ca.png)



![Image](https://user-images.githubusercontent.com/433958/213768114-01bc66f7-a2a2-4258-ade2-6786e2057f00.png)

**Comment by mauromorales** [comment]
Noticed that if I run `setupcon` while in the console and regenerate the QR then it looks good, so I'm going to see if running it at build time makes any difference
