### ISSUE TITLE
Switch to docsy

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#235]
**Is your feature request related to a problem? Please describe.**
Given the amount of [work](https://github.com/kairos-io/kairos/labels/area%2Fwebsite) that a base with astro.build brings, I've been wondering if we couldn't just switch to something more mainstream for FOSS projects like https://www.docsy.dev/

**Describe the solution you'd like**
Adapt our current graphic and create a custom land page/palette for docsy. In this way we inherit all the docsy functionalities and avoid the maintenance burden

**Describe alternatives you've considered**
Invest in building all from scratch

**Additional context**
Switching to docsy will reduce all the cards in [area/website](https://github.com/kairos-io/kairos/labels/area%2Fwebsite), to just adapt the landpage/docs graphics accordingly to our CSS style

**Comment by mudler** [comment]
See https://github.com/kairos-io/kairos/compare/docs-hugo?expand=1 for a starting point

**Comment by codrin-iftimie** [comment]
@mudler Using (this)[https://docs.astro.build/en/comparing-astro-vs-other-tools/#hugo-vs-astro] as a reference between comparing the two solutions. While they are comparable in terms of user experience, I think the level of customization hugo might be lacking. 
We can do some cool things using Astro since it can add dynamic interactions "on-demand", tabs, CLI like environments etc. Not sure whats the scope and how the docs might grow, but I hope new features will be needed.

I think we should see if there are issues in terms of developer experience. 
We could easily tackle all of the issues on the alrea/website bucket.

**Comment by mudler** [comment]
> @mudler Using (this)[https://docs.astro.build/en/comparing-astro-vs-other-tools/#hugo-vs-astro] as a reference between comparing the two solutions. While they are comparable in terms of user experience, I think the level of customization hugo might be lacking. We can do some cool things using Astro since it can add dynamic interactions "on-demand", tabs, CLI like environments etc. Not sure whats the scope and how the docs might grow, but I hope new features will be needed.
> 
> I think we should see if there are issues in terms of developer experience. We could easily tackle all of the issues on the alrea/website bucket.

A fair comparison should be done with docsy, not with hugo. Hugo by itself just gives basic building blocks, while docsy gives all the features set that typically a Foss project needs, more or less like Docusaurus does. I'm ok with astro, but I'm worried about the little bandwidth that we can invest to build such features by ourselves
