### ISSUE TITLE
Uki: installer went into black screen and then reboot without any installation

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2356]
**Kairos version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

I tried both auto-enroll and manually enrolling the keys via BIOS on a supermicro box, but neither of them worked.
The behavior is that after I choose the boot entry to install mode, it just went into black screen for 3-4min and then automatically rebooted
And after reboot, i could not see any bootable medium other than the installer iso itself.
**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

![image](https://github.com/kairos-io/kairos/assets/5505684/99b9b2e4-90b3-4bdc-8dfd-6b9f04b18e12)
![image](https://github.com/kairos-io/kairos/assets/5505684/ee628220-327f-4af1-a7bc-202d4dcdff28)

**Comment by Itxaka** [comment]
If secureboot is enabled, just the booting of the iso means that the keys are ok, otherwise with secureboot enabled and no custom keys, the iso would not even load (systemd-boot in the iso is signed with the same custom keys) so the key enrollment does not seem to be the problem here, unless secureboot is not enabled?

If secureboot is disabled then yeah, it doesnt seem to be installing the keys directly.


@nianyush can you check if secureboot is enabled on the firmware? 

If it is then it may be a size issue that the firmware is not properly dealing with somehow. Is there any firmware updates for it? What year is the firmware from?

**Comment by nianyush** [comment]
@Itxaka secure boot is enabled and i have installed keys manually. Its supermicro x10 series

**Comment by nianyush** [comment]
![Screenshot 2024-03-17 at 11 45 34 PM](https://github.com/kairos-io/kairos/assets/5505684/503f2b4d-5b66-44ec-99d1-4cddb782b56c)

**Comment by nianyush** [comment]
![Screenshot 2024-03-17 at 11 46 28 PM](https://github.com/kairos-io/kairos/assets/5505684/24b04cdc-565a-4b34-b348-f48bf4877b63)

**Comment by nianyush** [comment]
![Screenshot 2024-03-17 at 11 47 57 PM](https://github.com/kairos-io/kairos/assets/5505684/75e082a0-8bc3-4b2e-aedf-959049a11118)
EFI image size is 771MB

**Comment by jimmykarily** [comment]
@nianyush this was Ubuntu right? @mudler said you tried with Fedora and it worked. What was the size of the Fedora version? If it was smaller than 771Mb it's probably the size of the image again.

**Comment by nianyush** [comment]
@jimmykarily yes, i can confirm that this is related to size issue. Fedora image is around 260MB.

**Comment by mudler** [comment]
closing then as it is a Firmware/Hardware issue as we can't really do anything about it for the moment
