### ISSUE TITLE
bpfilter errors on alpine

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#277]
**Kairos version:**
1.1.3 up to 1.1.7

**CPU architecture, OS, and Version:**

**Describe the bug**
The system works, however, there are spammy messages about bp_filter:
![Schermata del 2022-10-24 17-59-42](https://user-images.githubusercontent.com/2420543/197571883-0f555dce-ec1a-4589-940b-81f2efc01920.png)

**To Reproduce**
Create an image with k3s enabled

**Expected behavior**
To not have spammy messages over the console, but most importantly, not have bpfilter errors

**Comment by mudler** [comment]
Maybe related to #194 ?

**Comment by mudler** [comment]
possibly a kernel-related issue: https://lore.kernel.org/lkml/20200730155527.GB1829@supreme/

**Comment by mudler** [comment]
Needs validation on master if this is still occuring with the Ubuntu kernel

**Comment by mudler** [comment]
mh. the fact that iptables by default is legacy, and not using the new versions might be causing this: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14058

**Comment by mudler** [comment]
still present

**Comment by christianprim** [comment]
alpine-ubuntu v1.2.0 on qemu: no messages any more. Will try later on bare metal.

**Comment by christianprim** [comment]
> alpine-ubuntu v1.2.0 on qemu: no messages any more. Will try later on bare metal.

I think, the messages disappeared only because the k3s-service wasn't started.

**Comment by christianprim** [comment]
In v1.2.0 this issue persists. When k3s is running the console gets flooded.
A temporary workaround is to disable console logging with `sudo dmesg -n 1`

**Comment by christianprim** [comment]
kairos-ubuntu and kairos-opensuse:

```
# dmesg | grep "Started bpfilter"
[  205.858934] Started bpfilter
# lsmod | grep bpfilter
bpfilter               16384  0
# modprobe bpfilter 
<empty, so it works>
```

but on kairos-alpine-ubuntu:

```
# dmesg | grep "Started bpfilter"
<empty>
# lsmod | grep bpfilter
<empty>
# modprobe bpfilter 
modprobe: ERROR: could not insert 'bpfilter': Bad address
```

**Comment by christianprim** [comment]
kairos-ubuntu and kairos-opensuse both use iptables-legacy as far as I could see. They both use the binaries from k3s since no other binaries were installed in the system.

Only `$ sudo /var/lib/rancher/k3s/data/current/bin/aux/iptables-legacy --list` shows the entries. So I think it must be legacy. Version from k3s: iptables v1.8.6 (legacy)

Maybe one could remove the iptables-binaries (version in alpine: iptables v1.8.8 (legacy)) from the image to check if it works with the binaries from k3s as with the other flavors. But since `modprobe bpfilter` fails, I'm not very confident.

(Sorry, I really don't have the time to build new images without iptables-package to test)

**Comment by christianprim** [comment]
I think I found the issue: the bpfilter kernel module uses a user-mode helper, which is compiled against glibc. Since alpine uses musl, this part of the kernel can't work. See the solution for k3os here: https://github.com/rancher/k3os/issues/498#issuecomment-639868105

That's bad news since you have to build the kernel with the patch applied.... (or maybe you find a working kernel (alpine?))

**Comment by christianprim** [comment]
@mudler: As far as I can see (https://git.alpinelinux.org/aports/tree/main/linux-lts/lts.x86_64.config?h=3.17-stable) Alpine doesn't compile the bpfilter-kernel-module in its own kernel. Could we simply blacklist it?

**Comment by christianprim** [comment]
@mudler: I've tested the blacklisting. It works!

```
stages:
  initramfs:
  - commands:
    - echo "install bpfilter /bin/false" > /etc/modprobe.d/blacklist_bpfilter.conf
```
(You may choose a better stage than initramfs to do it.)

I haven't tested if the firewall really does something. But the messages are now very similar to those found in opensuse and ubuntu. And since Alpine doesn't ship a kernel with bpfilter enabled I think this should work.

**Comment by mudler** [comment]
Hey @christianprim that's a great finding! awesome!

Do you feel to take a stab at it with a PR? we can use the `initramfs.before` stage so we can make sure it is available from the `initramfs` stage already in case of manual overrides.

re: bpfilter - I'd consider this somehow a workaround that is acceptable for the time being, we need to bring vanilla kernels in, but the challenge is that our initramfs is generated by dracut which is not currently supported in Alpine, thus will take a bit to get more to get there.

**Comment by mudler** [comment]
No worries - thank you! I've created one, let's see if looks good from the CI
