### ISSUE TITLE
[no-UKI] Make ISO images hybrid and with GPT to improve compatability

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#3063]
This allows to boot the ISO with different combination of HW for UKI: https://github.com/kairos-io/enki/pull/107 - we should have the same for non-UKI mode, for instance when booting with UEFI but with grub.

See also: https://github.com/kairos-io/kairos/issues/2547

**Comment by Itxaka** [comment]
Seems that the actual issue was not that the USB is not recognized, but the usb boots and it gets a grub shell because it cannot load the default grub.cfg for efi.

This seems to be a side issue of how efi booting works differently from livecd or usb in grub.
Looks like when booting from livecd, the efi artifacts are loaded from the efi image file BUT the livecd is mounted as root for grub.
When booting from usb it seems like the efi artifacts are loaded from the efi image AND the efi image is mounted as root for grub.

In both cases, grub is hardcoded to search for the grub config in /EFI/boot/grub.cfg (so alongside the grubx64.efi file)
When we build the ISO we only copy those artifacts on the ISO root, so you got the /EFI/boot/grub.cfg directly accessible when booting from livecd.
But when booting from usb the livecd is ignored and only the contents of the uefi.img are in the root, so /EFI/boot/grub.cfg does not exists.

This is fixed by copying it to both places so it works on both boot methods.
