### ISSUE TITLE
grub menu on raspberry pi is missing unicode font

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#507]
**Kairos version:**

```
NAME="kairos-opensuse-arm-rpi"
VERSION="v1.2.0-k3sv1.25.3+k3s1"
ID="kairos"
ID_LIKE="kairos-opensuse-arm-rpi"
VERSION_ID="v1.2.0-k3sv1.25.3+k3s1"
PRETTY_NAME="kairos-opensuse-arm-rpi v1.2.0-k3sv1.25.3+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-opensuse-arm-rpi"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse"
```

**CPU architecture, OS, and Version:**

```
Linux rpi4node 5.14.21-150400.24.28-default #1 SMP PREEMPT_DYNAMIC Mon Oct 10 15:21:12 UTC 2022 (f82da2c) aarch64 aarch64 aarch64 GNU/Linux
```
**Describe the bug**

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1231174/204557560-12a5ab68-b678-41f6-bc1a-9a96fce8fa6b.png">

**To Reproduce**

just reboot
**Expected behavior**

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/1231174/204560886-65d0a127-56fc-467b-9ebf-772e887cc561.png">

**Logs**

**Additional context**

**Comment by jimmykarily** [comment]
It could be related to this: https://github.com/kairos-io/kairos/issues/622 
Since we don't copy the grub config, maybe that's why we don't use the right font.

**Comment by mauromorales** [comment]
One thing I noticed is that `lsfonts` is empty. So I managed to update the config directly from the luet package, and the font seems to be properly loaded afterwards. However, this doesn't seem to fix the issue. Since we copy the fonts from opensuse's grub2 package, I also tried generating a completely new font, to ensure that no non-ascii characters are present, but again this didn't seem to fix the issue. At this point I'm convinced the font is properly configured but grub is not playing well with it, I wonder if it's a similar issue to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024447

**Comment by mauromorales** [comment]
![image](https://github.com/kairos-io/kairos/assets/433958/9a12e539-fba5-4540-b861-fc72e8ffe871)

Finally 😅

**Comment by mauromorales** [comment]
Needed to add `terminal_output gfxterm` in the configuration. Thanks to Linux from scratch for putting an example configuration :pray: https://linuxfromscratch.org/blfs/view/11.0/postlfs/grub-setup.html

Once the two PRs get merged I will do some QA in opensuse and ubuntu

**Comment by mauromorales** [comment]
shoot, the osbuilder version still needs to be bumped

**Comment by mauromorales** [comment]
ok, everything is in place. both flavors QAed
