### ISSUE TITLE
Improve kairos-agent upgrade list-releases output

### ISSUE THREAD

**Issue by dharmjit** [kairos-io/kairos#684]
**Kairos version:**
```
NAME="kairos-core-opensuse"
VERSION="v1.4.0"
ID="kairos"
ID_LIKE="kairos-core-opensuse"
VERSION_ID="v1.4.0"
PRETTY_NAME="kairos-core-opensuse v1.4.0"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
HOME_URL="https://github.com/kairos-io/kairos"
IMAGE_REPO="quay.io/kairos/core-opensuse"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/kairos"
VARIANT="core"
FLAVOR="opensuse"
```

**CPU architecture, OS, and Version:**
`Linux localhost 5.14.21-150400.24.38-default #1 SMP PREEMPT_DYNAMIC Fri Dec 9 09:29:22 UTC 2022 (e9c5676) x86_64 x86_64 x86_64 GNU/Linux`

**Describe the bug**
The `kairos-agent upgrade list-releases` command output the list of all releases irrespective of whether the current OS has K8s or not. Also, some of the versions are repeating. This is related to UX and in my mind should only show the versions which are relevant to the current OS. Also, I guess it's better to show the higher versions only and in case higher versions are not available, should return a useful message such as 'No upgrades available'.
```
kairos@localhost:~> sudo kairos-agent upgrade list-releases
v1.4.0
v1.3.2
v1.3.1
v1.3.0
v1.2.1
v1.2.0
v1.1.7
v1.1.6
v1.1.5
v1.1.4
v1.1.3
v1.1.2
v1.1.1
v1.1.0
v1.0.0
v1.0.0-rc3
v1.0.0-rc2
v1.0.0-rc1
v0.57.0
v0.57.0-rc2
v0.57.0-rc1
v0.57.0-alpha2
v0.57.0-alpha1
v1.24.3-56
v1.23.9-56
v1.22.12-56
v1.21.14-56
v1.23.6-53
v1.22.9-53
v1.21.12-53
v1.4.0
v1.3.2
v1.3.1
v1.3.0
v1.2.1
v1.2.0
v1.1.7
v1.1.6
v1.1.5
v1.1.4
v1.1.3
v1.1.2
v1.1.1
v1.1.0
v1.0.0
v1.0.0-rc3
v1.0.0-rc2
v1.0.0-rc1
v0.57.0
v0.57.0-rc2
v0.57.0-rc1
v0.57.0-alpha2
v0.57.0-alpha1
v1.24.3-56
v1.23.9-56
v1.22.12-56
v1.21.14-56
v1.23.6-53
v1.22.9-53
v1.21.12-53
```

**To Reproduce**
Run `kairos-agent upgrade list-releases`

**Comment by Itxaka** [comment]
good point, we should probably use the os-release GITHUB_REPO list if available to list the versions of that repo only. so if you build from MYORG/MYREPO we show those releases. 

Also some flags to --show-all-releases or even a --regex to filter them would be nice!

**Comment by Itxaka** [comment]
oh it already uses the GITHUB_REPO, nais :)

**Comment by mudler** [comment]
@mauromorales are you working on this?

**Comment by mauromorales** [comment]
@mudler not currently, I only addressed the bug with duplicated lists for the other two requests, I think they need to be planned or at least decided on:

- Only showing newer releases. What if the user actually wants to downgrade? Or should we introduce a downgrade command and only list older releases there? Or, like Itxaka is suggesting, we can add some sorting/filtering mechanism
- The issue about having an upgrade that isn't based on the same OS. Should we then not display other releases if they are not based in the same OS? Is there any scenario where the user might want to switch OS, and we would be blocking them to do so?

If you have a clear approach, then I'm happy to create the tickets and proceed. Otherwise, I can bring the topic again to our next planning.

**Comment by jimmykarily** [comment]
Various improvements have been made to the `list-releases` output since this ticket was opened.

First of all, the releases returned can be controlled by passing options to the command:

```
localhost:/home/kairos # kairos-agent upgrade list-releases --help
NAME:
   kairos-agent upgrade list-releases

USAGE:
   kairos-agent upgrade list-releases [command options] [arguments...]

DESCRIPTION:
   List all available releases versions

OPTIONS:
   --output value  Output format (json|yaml|terminal)
   --pre           Include pre-releases (rc, beta, alpha) (default: false)
   --all           Include older releases (default: false)
   --help, -h      show help
```

Also the output looks nicer:

```
localhost:/home/kairos # kairos-agent upgrade list-releases --all
Current image:
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.2-k3sv1.27.9-k3s1

Available releases (all):
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.4-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.4-k3sv1.27.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.3-k3sv1.29.3-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.3-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.3-k3sv1.27.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.2-k3sv1.29.3-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.2-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.1-k3sv1.29.0-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.1-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.1-k3sv1.27.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.0-k3sv1.29.0-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.0-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v3.0.0-k3sv1.27.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.5.0-k3sv1.29.0-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.5.0-k3sv1.28.5-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.5.0-k3sv1.27.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.3-k3sv1.28.2-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.3-k3sv1.27.6-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.3-k3sv1.26.9-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.2-k3sv1.28.2-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.2-k3sv1.27.6-k3s1
quay.io/kairos/opensuse:leap-15.5-standard-amd64-generic-v2.4.2-k3sv1.26.9-k3s1
```

Having said that, there is a bug that can cause it to panic: https://github.com/kairos-io/kairos/issues/2440
but that's is being tracked on that other issue.
I think the original request has been fulfilled. I'll close this. Feel free to re-open if you think something is missing.
