### ISSUE TITLE
:seedling: Split elemental-cli into a lifecycle manager for the system (install/upgrade) and a building component

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#711]
The building bits should be part of osbuilder, and renamed accordingly.

This is a "cosmetical change" as the lib will still be in one place, and just the cmd/bin starters 

![Image](https://github.com/kairos-io/kairos/assets/2420543/f3a6fdae-03ac-49d5-b7ce-5483b0375759)

## Action items

- [x] Extract the building functionality to a new binary
- [x] Use the new "building" binary in osbuilder and auroraboot (instead of elemental-cli). osbuilder/auroraboot should no longer depend on elemental-cli (just the new binary).
- [x] Rename elemental-cli to something that reflects its "installer/upgrader" nature.
- [x] Use the new "installer/upgrader" binary in kairos (replacing elemental-cli everywhere). For a couple of releases, let's maintain a symlink pointing elemental-cli to the new binary. We should show a deprecation warning.
- [x] Adapt the architecture docs which refers to elemental-toolkit and elemental-cli and adapt accordingly. 
- [x] get rid of manual pinning here: https://github.com/kairos-io/osbuilder/blob/d8a56badc11aa1a9f797e45ff82c813075f41ed8/tools-image/Dockerfile#L26

**Comment by Itxaka** [comment]
But wait! There is more: https://github.com/kairos-io/kairos/discussions/1167

**Comment by jimmykarily** [comment]
We'll do this: https://github.com/kairos-io/kairos/issues/1210

**Comment by mudler** [comment]
@Itxaka @jimmykarily I think we can close this, right? or there is anything pending? maybe we just have to get rid of the elemental-cli references?

**Comment by jimmykarily** [comment]
This issue describes the original idea. Since then, we decided to merge the lifecycle parts of elemental-cli to the kairos-agent and the building parts somewhere in the osbuilder (which hasn't happened yet). Also the kairos-agent still shells out to elemental-cli for some of the things it does. In other words, we need to:

- [ ] stop shelling out to elemental-cli from kairos-agent, copy over the code and make it native functionality in kairos-agent
- [ ] Move the building functionality to osbuilder
- [ ] archive the elemental-cli repository
- [ ] remove all references to elemental-cli from docs/code/everywhere

I don't think this is the right issue to track this work, after all it describes an older idea, but I don't know which issue it the right one. Let's discuss this in tomorrow's planning an make sure we capture the remaining work.

**Comment by jimmykarily** [comment]
Moved some work here: https://github.com/kairos-io/kairos/issues/1633
