### ISSUE TITLE
:sparkles: Add versioning to docs

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#739]
The docs currently just contain the latest version of the documentation. I'd like us to introduce versioning, so the documentation matches the versions of the Kairos releases. This would be a better experience for the end user because they can choose the specific Kairos release they are using, and get examples and other information specific to their release. Currently, to know whether a feature or not is available, they'd need to go through the changelogs or the code itself to figure out if the feature was already available in the image they are using.

See https://www.docsy.dev/docs/adding-content/versioning/

**Comment by Itxaka** [comment]
doc versioning seems to be to copy the docs into their own dir (so docs/v2.3.0, docs/master) and having the versions marked in the config file.

A bit crude to be honest, something like readthedocs autogenerated the docs for the proper version 😭 

We may be able to automate it somehow as part of cutting a new docs release, but at least a manual conversion currently in order to fix the current state (so have the v2.3.0 docs under v2.3.x and master under master) would eb a good start to see what breaks.

**Comment by mauromorales** [comment]
sounds good to me. We should also add somewhere on the navbar or other place that is very visible, which version you're looking into and when it's no version at all it says something like "edge" that way we also don't block ourselves from updating docs before releasing a feature

**Comment by Itxaka** [comment]
> sounds good to me. We should also add somewhere on the navbar or other place that is very visible, which version you're looking into and when it's no version at all it says something like "edge" that way we also don't block ourselves from updating docs before releasing a feature

This comes by default with docsy if you add more than one version, pretty handy!

**Comment by mauromorales** [comment]
fantastic

**Comment by Itxaka** [comment]
had a look at this.

versioning support is pretty terrible, even if its supported out of the box.

So we should do branch versioning with netlify: https://docs.netlify.com/domains-https/custom-domains/automatic-deploy-subdomains/

And use the hugo versioning to redirect to the proper url like so:

```
# Add your release versions here
[[params.versions]]
  version = "master"
  url = "https://master.kairos.io/docs"

[[params.versions]]
  version = "v2.4.0"
  url = "https://v2.4.0.kairos.io/docs"

[[params.versions]]
  version = "v2.3.0"
  url ="https://v2.3.0.kairos.io/docs"
```

Otherwise, the actual, state of it its pretty terrible, redirects, duplicating the full docs dir and so on...and its not without issues...

**Comment by mauromorales** [comment]
@mudler can you check if with our plan, we can do branch subdomains? [1] this way we could create a branch for each release.


[1]: https://docs.netlify.com/domains-https/custom-domains/multiple-domains/#branch-subdomains

**Comment by mauromorales** [comment]
Mudler did some changes to have branch subdomains working on netlify. We tested it by creating one and it does trigger a build and gets published under https://subdomain-branches--kairos-io.netlify.app/ but we are still waiting for DNS propagation to see if it's actually working under https://subdomain-branches.kairos.io

**Comment by mauromorales** [comment]
checked today and is still not working. Even if the resolution time was to 2 days I think it's probably not working ... doesn't seem like any other subdomain was affected either

**Comment by mauromorales** [comment]
This came back in the retro again, checked the DNS, and it's still not working

**Comment by jimmykarily** [comment]
We now have a solution right? e.g. https://kairos.io/v3.0.1/docs/

@mauromorales should we close this?
