### ISSUE TITLE
:bug: Framework image contains optional components

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/kairos#776]
**Kairos version:**
v1.5.0

**Describe the bug**
The Kairos framework images contain  the following dracut modules which are optional and not present in all OSes. Consequently kernel initrd builds fail in specific systems. These files either need to be removed or omitted using other packages

./etc/dracut.conf.d/90-kairos-resolved.conf
./etc/dracut.conf.d/90-kairos-sysext.conf

**To Reproduce**
Install framework package without systemd-sysext ,systemd-resolved and sytemd-networkd. The initrd compiles fail.

**Comment by mudler** [comment]
Thanks for filing up the issue @venkatnsrinivasan !

**Comment by mudler** [comment]
This should be now fixed by https://github.com/kairos-io/kairos/issues/755. Next releases will have framework images per-flavor.

Meanwhile, framework images from master should be published as well, so we can use that for testing. Closing this in favor of specific issues after trying the flavor-specific images (I think fedora ones would fit your case here).
